# Generated by Django 2.1.4 on 2018-12-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommitChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_investment', models.FloatField()),
                ('income_for_life', models.FloatField()),
                ('years', models.FloatField()),
                ('annual_interest_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_investment', models.FloatField()),
                ('annual_investment', models.FloatField()),
                ('years', models.FloatField()),
                ('annual_interest_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RetireChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_investment', models.FloatField()),
                ('annual_investment', models.FloatField()),
                ('income_for_life', models.FloatField()),
                ('annual_interest_rate', models.FloatField()),
            ],
        ),
    ]
